DROP TABLE IF EXISTS test_drive_requests CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS vehicle_media CASCADE;
DROP TABLE IF EXISTS custom_order_features CASCADE;
DROP TABLE IF EXISTS custom_orders CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS model_features CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS models CASCADE;
DROP TABLE IF EXISTS transmissions CASCADE;
DROP TABLE IF EXISTS engines CASCADE;
DROP TABLE IF EXISTS body_types CASCADE;
DROP TABLE IF EXISTS dealerships CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();

DROP TYPE IF EXISTS test_drive_status;
DROP TYPE IF EXISTS media_type;
DROP TYPE IF EXISTS custom_order_status;
DROP TYPE IF EXISTS order_status;
DROP TYPE IF EXISTS drive_type;
DROP TYPE IF EXISTS transmission_type;
DROP TYPE IF EXISTS fuel_type;
DROP TYPE IF EXISTS user_role;
